// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDerLq7Y2ps4W9J-wJtawDDxlxvrcRHM_U',
    appId: '1:96516272822:web:95ad07660a36f5f1772c17',
    messagingSenderId: '96516272822',
    projectId: 'innogeeks-app',
    authDomain: 'innogeeks-app.firebaseapp.com',
    storageBucket: 'innogeeks-app.appspot.com',
    measurementId: 'G-XHTG7QY947',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8jE44H10k3rPpyOGF3-2jBUYdkpjMuSg',
    appId: '1:96516272822:android:8b516823ae5fdc29772c17',
    messagingSenderId: '96516272822',
    projectId: 'innogeeks-app',
    storageBucket: 'innogeeks-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPH7eJxHuCr7pO5EKz_4egqZ1dCEXxsx8',
    appId: '1:96516272822:ios:0b31133dd3b7e580772c17',
    messagingSenderId: '96516272822',
    projectId: 'innogeeks-app',
    storageBucket: 'innogeeks-app.appspot.com',
    iosBundleId: 'com.example.innogeeksApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPH7eJxHuCr7pO5EKz_4egqZ1dCEXxsx8',
    appId: '1:96516272822:ios:0b31133dd3b7e580772c17',
    messagingSenderId: '96516272822',
    projectId: 'innogeeks-app',
    storageBucket: 'innogeeks-app.appspot.com',
    iosBundleId: 'com.example.innogeeksApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDerLq7Y2ps4W9J-wJtawDDxlxvrcRHM_U',
    appId: '1:96516272822:web:875e5848aba9b5fb772c17',
    messagingSenderId: '96516272822',
    projectId: 'innogeeks-app',
    authDomain: 'innogeeks-app.firebaseapp.com',
    storageBucket: 'innogeeks-app.appspot.com',
    measurementId: 'G-ZTL6KQQNDM',
  );
}
